defaults:
  - base
  - _self_

project: text2semantic_finetune_dual_ar
max_length: 4096
pretrained_ckpt_path: checkpoints/s2-pro

# Lightning Trainer
trainer:
  accumulate_grad_batches: 4
  gradient_clip_val: 1.0
  gradient_clip_algorithm: "norm"
  max_steps: 400
  precision: bf16-true
  limit_val_batches: 10
  val_check_interval: 50
  # strategy:
  #   find_unused_parameters: true
  #   static_graph: true 

# Dataset Configuration
tokenizer:
  _target_: fish_speech.tokenizer.FishTokenizer
  model_path: ${pretrained_ckpt_path}

# Dataset Configuration
train_dataset:
  _target_: fish_speech.datasets.semantic.AutoTextSemanticInstructionIterableDataset
  proto_files:
    - data/protos
  tokenizer: ${tokenizer}
  causal: false
  max_length: ${max_length}
  use_speaker: false
  interactive_prob: 1.0

val_dataset:
  _target_: fish_speech.datasets.semantic.AutoTextSemanticInstructionIterableDataset
  proto_files:
    - data/protos
  tokenizer: ${tokenizer}
  causal: false
  max_length: ${max_length}
  use_speaker: false
  interactive_prob: 1.0

data:
  _target_: fish_speech.datasets.semantic.SemanticDataModule
  train_dataset: ${train_dataset}
  val_dataset: ${val_dataset}
  num_workers: 4
  batch_size: 1
  tokenizer: ${tokenizer}
  max_length: ${max_length}

# Model Configuration
model:
  _target_: fish_speech.models.text2semantic.lit_module.TextToSemantic
  model: 
    _target_: fish_speech.models.text2semantic.llama.BaseTransformer.from_pretrained
    path: ${pretrained_ckpt_path}
    load_weights: true
    max_length: ${max_length}
    lora_config: null

  optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 1e-5
    weight_decay: 0.01
    betas: [0.9, 0.95]
    eps: 1e-5

  lr_scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    _partial_: true
    T_max: 400
    eta_min: 1e-6

# Callbacks
callbacks:
  model_checkpoint:
    every_n_train_steps: 100
  audio_sample:
    _target_: fish_speech.callbacks.AudioSampleCallback
    text: "大家好我的名字叫黄诗慧,英文名叫Trump"
    codec_checkpoint_path: checkpoints/s2-pro/codec.pth
    reference_audio_path: references/frobit/chunk_0640.wav
    reference_text: "常指财务或经济上的成功。我们来听两个例句。接着来看 boom。我们通常用动词 boom 表示数量或人气激增，常用来谈论产品、企业的销量迅速增长，人或物迅速流行起来。注意，与 prosper 相比，boom 更突出发展的迅速。"
    audio_format: mp3
